## 1) Importar bibliotecas

In [1]:
import tensorflow as tf
import numpy as np

## 2) Criar dataset

In [3]:
data = tf.constant(
    value = [
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0],
    ]
)

data = tf.reshape(
    tensor = data,
    shape = (1, 8, 8, 1)
)

print(data)

tf.Tensor(
[[[[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   [1]
   [1]
   [0]
   [0]
   [0]]]], shape=(1, 8, 8, 1), dtype=int32)


## 3) Entendendo CNN

### 3.1) Criando modelo

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(shape = (8, 8, 1)),
    tf.keras.layers.Conv2D(
        filters = 1,
        kernel_size = (3, 3),
        activation = "linear",
    )
])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 6, 6, 1)        │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10 (40.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.weights

[<Variable path=sequential/conv2d/kernel, shape=(3, 3, 1, 1), dtype=float32, value=[[[[ 0.5213629 ]]
 
   [[-0.30209252]]
 
   [[-0.43792614]]]
 
 
  [[[ 0.04257339]]
 
   [[-0.48956788]]
 
   [[-0.11240569]]]
 
 
  [[[ 0.4280026 ]]
 
   [[ 0.03243321]]
 
   [[ 0.42855716]]]]>,
 <Variable path=sequential/conv2d/bias, shape=(1,), dtype=float32, value=[0.]>]

In [48]:
model.weights

[<Variable path=sequential/conv2d/kernel, shape=(3, 3, 1, 1), dtype=float32, value=[[[[0.]]
 
   [[1.]]
 
   [[0.]]]
 
 
  [[[0.]]
 
   [[1.]]
 
   [[0.]]]
 
 
  [[[0.]]
 
   [[1.]]
 
   [[0.]]]]>,
 <Variable path=sequential/conv2d/bias, shape=(1,), dtype=float32, value=[0.]>]

### 3.2) Definindo kernel teste

In [45]:
kernel = tf.constant(value = [
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
])

kernel = tf.reshape(tensor = kernel, shape = (3, 3, 1, 1))

print(kernel)

tf.Tensor(
[[[[0]]

  [[1]]

  [[0]]]


 [[[0]]

  [[1]]

  [[0]]]


 [[[0]]

  [[1]]

  [[0]]]], shape=(3, 3, 1, 1), dtype=int32)


In [46]:
bias = tf.constant([0.0])

weights = [kernel, bias]

weights

[<tf.Tensor: shape=(3, 3, 1, 1), dtype=int32, numpy=
 array([[[[0]],
 
         [[1]],
 
         [[0]]],
 
 
        [[[0]],
 
         [[1]],
 
         [[0]]],
 
 
        [[[0]],
 
         [[1]],
 
         [[0]]]], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>]

In [47]:
model.set_weights(weights)

In [49]:
y_pred = model.predict(
    data
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 316ms/step


In [65]:
for i in y_pred[0]:
    for j in i:
        print(j, end="")
    print()

[0.][0.][3.][3.][0.][0.]
[0.][0.][3.][3.][0.][0.]
[0.][0.][3.][3.][0.][0.]
[0.][0.][3.][3.][0.][0.]
[0.][0.][3.][3.][0.][0.]
[0.][0.][3.][3.][0.][0.]


In [74]:
tensor = tf.constant(
    value = [
        [7, 2, 3, 3, 8],
        [4, 5, 3, 8, 4],
        [3, 3, 2, 8, 4],
        [2, 8, 7, 2, 7],
        [5, 4, 4, 5, 4]
    ]
)

tensor = tf.reshape(
    tensor = tensor,
    shape = (1, 5, 5, 1)
)

print(tensor)

tf.Tensor(
[[[[7]
   [2]
   [3]
   [3]
   [8]]

  [[4]
   [5]
   [3]
   [8]
   [4]]

  [[3]
   [3]
   [2]
   [8]
   [4]]

  [[2]
   [8]
   [7]
   [2]
   [7]]

  [[5]
   [4]
   [4]
   [5]
   [4]]]], shape=(1, 5, 5, 1), dtype=int32)


In [77]:
new_model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(
        shape = (5, 5, 1)
    ),
    tf.keras.layers.Conv2D(
        filters = 1,
        kernel_size = (3, 3),
        strides = (1, 1),
        activation = "linear",
    )
])

new_model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_7 (Conv2D)               │ (None, 3, 3, 1)        │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10 (40.00 B)

 Trainable params: 10 (40.00 B)

 Non-trainable params: 0 (0.00 B)

In [80]:
kernel = tf.constant(
    value = [
        [1, 0, -1],
        [1, 0, -1],
        [1, 0, -1],
    ]
)

kernel = tf.reshape(
    tensor = kernel,
    shape = (3, 3, 1, 1)
)

kernel

<tf.Tensor: shape=(3, 3, 1, 1), dtype=int32, numpy=
array([[[[ 1]],

        [[ 0]],

        [[-1]]],


       [[[ 1]],

        [[ 0]],

        [[-1]]],


       [[[ 1]],

        [[ 0]],

        [[-1]]]], dtype=int32)>

In [78]:
new_model.weights

[<Variable path=sequential_7/conv2d_7/kernel, shape=(3, 3, 1, 1), dtype=float32, value=[[[[-0.23229629]]
 
   [[ 0.03276962]]
 
   [[-0.16422358]]]
 
 
  [[[ 0.44761884]]
 
   [[ 0.321218  ]]
 
   [[-0.5652656 ]]]
 
 
  [[[-0.18910623]]
 
   [[ 0.4613695 ]]
 
   [[ 0.22010314]]]]>,
 <Variable path=sequential_7/conv2d_7/bias, shape=(1,), dtype=float32, value=[0.]>]

In [81]:
new_model.set_weights(
    [
        kernel, tf.constant([0.0])
    ]
)

In [83]:
new_model.predict(
    tensor
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 240ms/step


array([[[[ 6.],
         [-9.],
         [-8.]],

        [[-3.],
         [-2.],
         [-3.]],

        [[-3.],
         [ 0.],
         [-2.]]]], dtype=float32)