## 1) Importar bibliotecas

In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## 2) Ler base de dados

In [13]:
tensor1 = tf.constant([[1, 3, 7], [6, 9, 5]])
tensor2 = tf.constant([[6, 4, 0, 2], [5, 5, 1, 2], [7, 8, 0, 3]])

tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 70,  75,   3,  29],
       [116, 109,   9,  45]], dtype=int32)>

In [14]:
tensor1 @ tensor2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 70,  75,   3,  29],
       [116, 109,   9,  45]], dtype=int32)>

In [10]:
tensor2


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[6, 4, 0],
       [5, 5, 1]], dtype=int32)>